packages:
  - apps/api
  - apps/blog
  - apps/dashboard
  # - apps/landing
  - packages/auth
  - packages/config/*
  - packages/db
  - packages/emails
  - packages/common
  - packages/notifications
  - packages/ui
  - packages/zact
  # TODO: REMOVE
  - packages/adapter-drizzle
