name: 🐞 Bug Report
description: Create a bug report to help us improve
title: "bug: "
labels: ["🐞❔ unconfirmed bug"]
assignees:
  - dichioniccolo
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Link to reproduction
      description: Please provide a link to a reproduction of the bug. Issues without a reproduction repo may be ignored.
    validations:
      required: true
  - type: input
    attributes:
      label: Which browser are you using? (if relevant)
      description: 'Please specify the exact version. For example: Chrome 100.0.4878.0'